#!/bin/bash
#%depon: mounts
#%type: daemon
#%notify: 3
#%restart: always
#%start-timeout: 10s
mkdir -p /run/dbus
dbus-uuidgen --ensure
exec dbus-daemon --system --nofork --nopidfile --print-address=3
