#!/bin/bash
#%onfail: shell
while read -r _ _ _ _ mp opts _; do
	[ "$mp" = / ] && root_opts=$opts
done < /proc/self/mountinfo
[[ ,$root_opts, == *,ro,* ]] || exit 0
fsck -T -a /
(($? < 2)) || exit 1
exec mount -o remount,rw /
