#!/bin/bash
#%depon: dbus, udev, loopback
#%type: daemon
#%notify: 3
#%restart: always
#%start-timeout: 10s
{ gdbus wait --system org.freedesktop.NetworkManager && echo >&3; } &
exec 3>&- NetworkManager --no-daemon
